In [1]:
import pandas as pd 
df = pd.read_excel('customer_purchase_data.xlsx')

In [2]:
df.head(10)

,CustomerID,Age,Gender,Item,Purchase Category,Purchase Location,Size,Color,Season,Review Rate,Subscription Status,Shipping Type,Discount Amount,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,CUST001,19,Female,Jeans,Clothing,Gurugram,M,Blue,Spring,5,Yes,Next Day Air,0,Yes,2,Debit Card,Monthly
1,CUST002,56,Male,Shirt,Clothing,Dehradun,M,Brown,Winter,2,No,Free Shipping,0,Yes,22,PayPal,Quarterly
2,CUST003,27,Male,Dress,Clothing,Hyderabad,S,White,Winter,1,No,Free Shipping,100,Yes,23,PayPal,Weekly
3,CUST004,23,Female,Sandals,Footwear,Chandigarh,L,Beige,Summer,1,Yes,Express,100,Yes,7,Credit Card,Annually
4,CUST005,47,Female,Dress,Clothing,Bangalore,L,Grey,Summer,3,Yes,Express,300,Yes,5,PayPal,Annually
5,CUST006,58,Male,Dress,Clothing,Hyderabad,S,Red,Spring,3,No,Free Shipping,0,Yes,18,UPI,Monthly
6,CUST007,43,Female,Hoodie,Clothing,Bangalore,L,Blue,Summer,5,No,Next Day Air,200,No,7,Debit Card,Annually
7,CUST008,21,Male,Jeans,Clothing,Bangalore,M,Pink,Spring,4,No,Next Day Air,300,No,17,Credit Card,Weekly
8,CUST009,35,Female,Shirt,Clothing,Mumbai,L,Pink,Summer,4,Yes,Free Shipping,300,Yes,16,Credit Card,Quarterly
9,CUST010,56,Male,Shirt,Clothing,Bangalore,L,Blue,Spring,5,No,Next Day Air,0,Yes,11,UPI,Monthly

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              50 non-null     str
 1   Age                     50 non-null     int64
 2   Gender                  50 non-null     str
 3   Item                    50 non-null     str
 4   Purchase Category       50 non-null     str
 5   Purchase Location       50 non-null     str
 6   Size                    50 non-null     str
 7   Color                   50 non-null     str
 8   Season                  50 non-null     str
 9   Review Rate             50 non-null     int64
 10  Subscription Status     50 non-null     str
 11  Shipping Type           50 non-null     str
 12  Discount Amount         50 non-null     int64
 13  Promo Code Used         50 non-null     str
 14  Previous Purchases      50 non-null     int64
 15  Payment Method          50 non-null     str
 16  Frequency of Purchases  50 non-null     str
dtypes: int64(4), str(13)
memory usage: 6.8 KB

In [8]:
df.describe()

             Age  Review Rate  Discount Amount  Previous Purchases
count  50.000000     50.00000        50.000000           50.000000
mean   38.480000      2.98000       148.000000           13.120000
std    13.650506      1.33233       117.785693            7.330785
min    19.000000      1.00000         0.000000            0.000000
25%    26.250000      2.00000        12.500000            7.000000
50%    35.500000      3.00000       150.000000           12.500000
75%    52.000000      4.00000       250.000000           20.250000
max    60.000000      5.00000       300.000000           25.000000

In [9]:
df.isnull().sum()

CustomerID                0
Age                       0
Gender                    0
Item                      0
Purchase Category         0
Purchase Location         0
Size                      0
Color                     0
Season                    0
Review Rate               0
Subscription Status       0
Shipping Type             0
Discount Amount           0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

### Create a Column for age_Group.

In [25]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace('_','')

In [26]:
df.columns

Index(['customerid', 'age', 'gender', 'item', 'purchase category',
       'purchase location', 'size', 'color', 'season', 'review rate',
       'subscription status', 'shipping type', 'discount amount',
       'promo code used', 'previous purchases', 'payment method',
       'frequency of purchases'],
      dtype='str')

In [27]:
labels = ['Young Adult' , 'Adult' , 'Middle-aged' , 'Senior'] 
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [28]:
df[['age' , 'age_group']].head(10)

   age    age_group
0   19  Young Adult
1   56       Senior
2   27        Adult
3   23  Young Adult
4   47  Middle-aged
5   58       Senior
6   43  Middle-aged
7   21  Young Adult
8   35        Adult
9   56       Senior

### Purchase column purhase_frequency_days

In [29]:
frequency_mapping = {
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Annually' : 365
}
df['purchase_frequency_days'] = df['frequency of purchases'].map(frequency_mapping)

In [31]:
df[['purchase_frequency_days','frequency of purchases']].head(20)

    purchase_frequency_days frequency of purchases
0                        30                Monthly
1                        90              Quarterly
2                         7                 Weekly
3                       365               Annually
4                       365               Annually
5                        30                Monthly
6                       365               Annually
7                         7                 Weekly
8                        90              Quarterly
9                        30                Monthly
10                       30                Monthly
11                       30                Monthly
12                       30                Monthly
13                        7                 Weekly
14                       30                Monthly
15                        7                 Weekly
16                        7                 Weekly
17                      365               Annually
18                      365               Annually
19                       30                Monthly

### code for connecting mysql

In [32]:
import pymysql

db = pymysql.connect(
    host="127.0.0.1",
    user="root",
    password="shraddha17",
    database="customerdata"
)

cur = db.cursor()

In [33]:
cursor = db.cursor()

cursor.execute("SHOW TABLES")

for table in cursor:
    print(table)

('customer_purchase_data',)